name: platzi_random_forest
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - jupyter
  - jupyterlab
  - pip
  - python=3.11
  - pip:
    - pyhere
    - scikit-learn
    - setuptools==57.5.0
    - regressors
    - numpy
  - pandas
  - matplotlib
  - seaborn
